### ISSUE TITLE
Request for Code Integration of SVD-LLM with GPTQ

### ISSUE THREAD

**Issue by pvtien96** [AIoT-MLSys-Lab/SVD-LLM#1]
Hello,

Firstly, I want to express my gratitude for the fascinating work you've been doing. It's been inspiring.

I've recently come across your paper where you describe the integration of SVD-LLM with GPTQ, and I'm eager to explore the implementation further.
Could you please share the code where you've integrated SVD-LLM with GPTQ as described in the paper?

Your assistance in providing access to this code would be appreciated. Thank you for your time and consideration.

**Comment by tuidan** [comment]
Hi, thank you for your feedback! We will add a guidance of how to combine SVD-LLM and GPTQ for compression in this week.

We will let you know soon.

Thanks!

**Comment by tuidan** [comment]
Hi! Sorry for the late response. We have updated the code and now you can run `bash svdllm_gptq.sh` to compress LLaMA-7B with SVD-LLM and GPTQ.
