### ISSUE TITLE
Questions about running codes

### ISSUE THREAD

**Issue by xiaxin1998** [AIoT-MLSys-Lab/SVD-LLM#13]
I run 'bash compress_llama.sh' but I got an error 
FileNotFoundError: [Errno 2] No such file or directory: 'whitening/jeffwan_llama_7b_hf_whitening_0.2.pt'

In the bash, the ratio is 0.2 and the evaluation command requires jeffwan_llama_7b_hf_whitening_0.2.pt, but when saving models the name of saved model is 'jeffwan_llama_7b_hf_whitening_only_0.8.pt'. Is the bash command wrong? 
I revised the second and third command to my saved model name 'jeffwan_llama_7b_hf_whitening_only_0.8.pt'. Am I correct?

Thanks

**Comment by tuidan** [comment]
Yes, the name should be modified to "jeffwan_llama_7b_hf_whitening_only_0.8.pt". Thanks for pointing out the mistake.
