### ISSUE TITLE
Is SVDLLM also applicable in encoder-decoder models?

### ISSUE THREAD

**Issue by xiaxin1998** [AIoT-MLSys-Lab/SVD-LLM#14]
As described in the title, if this method can be used to compress encoder-decoder model, what steps I should do? Can you tell me the difference of the method on encoder-decoder models?

Thanks very much.

**Comment by tuidan** [comment]
Yes. Here are the steps:

1. Modify the weight name in the `whitening` function in `SVDLLM.py`
2. Modify the original `modeling_xxx.py` file in transformers package (xxx is the name of the model you want to compress). Replace the original weight layer with the decomposed weight layer and store the modified file in `component` directory.

I will also add an example of compressing Bert with SVDLLM.

**Comment by etomoscow** [comment]
> Yes. Here are the steps:
> 
>     1. Modify the weight name in the `whitening` function from line 130 to line 181 in `SVDLLM.py`
> 
>     2. Modify the original `modeling_xxx.py` file in transformers package (xxx is the name of the model you want to compress). Replace the original weight layer with the decomposed weight layer and store the modified file in `component` directory.  `component/svd_llama.py` is an example of how to modify it.
> 
> 
> I will also add an example of compressing Bert with SVDLLM.

Have you added example of BERT compression with SVD-LLM?
