### ISSUE TITLE
GQA architecture reproduce problem, Mistral-7B-v0.1 and Llama-3-8B

### ISSUE THREAD

**Issue by Ppaddington** [AIoT-MLSys-Lab/SVD-LLM#20]
For Mistral-7B-v0.1 20% compression ratio, PPL after pruning: {'wikitext2': 245.2660781818917}, the pruned ppl for Llama-3-8B is also bad like Mistral-7B.
Could you tell me how to reproduce the results in Table 2? Thanks a lot.

The command is as follows.
python SVDLLM.py --step 1 --model /data/Mistral-7B-v0.1 --ratio 0.2 --whitening_nsamples 256 --model_seq_len 4096 --dataset wikitext2 --seed 3 --save_path SVDLLM --DEV cuda
python SVDLLM.py --step 4 --model_path SVDLLM

By the way, for LLaMA 2-7B 20% compression ratio, PPL after pruning: {'wikitext2': 8.253116897498987} is also different from 6.07 (↓40%) of Table 2.
Looking forward to your reply. Thanks a lot!

**Comment by Ppaddington** [comment]
Thanks for your reply. 
For GQA architecture models, I will check transformers version and configs.
I understood only high compression ratios (recommended ratio > 0.3) need LoRA fine-tuning. 

Good luck!

**Comment by mi-zhang** [comment]
Thank you for your understanding. We really appreciate it.

**Comment by tuidan** [comment]
Hi, thanks for your interest. May I ask do you have any other concerns? Can I close this issue? We promise to update and open-source all the code upon acceptance.

Thank you for your insightful feedback!

**Comment by Ppaddington** [comment]
> Hi, thanks for your interest. May I ask do you have any other concerns? Can I close this issue? We promise to update and open-source all the code upon acceptance.
> 
> Thank you for your insightful feedback!

OK
Good luck!

**Comment by ZY123-GOOD** [comment]
> Mistral-7B-v0.1

Have you encountered this issue while using the mistral_v1.0 model: Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 40 column 3? Could you please advise on how to resolve it

**Comment by ZY123-GOOD** [comment]
> Hi, thanks for your interest in our project. I'm glad to see so many questions about our project. Here are our clarifications:
> 
> * This repo only contains the code of SVD-LLM in NeurIPS version (see this [paper](https://arxiv.org/abs/2403.07378) as mentioned in our [README](https://github.com/AIoT-MLSys-Lab/SVD-LLM/blob/main/README.md)), which is significantly different from our ICLR version. For the ICLR version's SVD-LLM, we have added the parameter update with sequential Low-rank Approximation, which is in fact a kind of sequential LoRA fine-tuning, to further enhance the accuracy after applying truncation-aware data whitening.
> * The command `python SVDLLM.py --step 1 --model /data/Mistral-7B-v0.1 --ratio 0.2 --whitening_nsamples 256 --model_seq_len 4096 --dataset wikitext2 --seed 3 --save_path SVDLLM --DEV cuda` is only to run the truncation-aware data whitening. Before you use `python SVDLLM.py --step 4 --model_path SVDLLM` to test the compressed LLM's PPL, you still need to call `PEFT` Library first to update W_u and then W_v to reproduce the result in our ICLR submission.
> * The Mistral-7B-v0.1's compression accuracy looks odd. In our experiments, we set the seq_len in both the whitening and evaluation stages to 2048. We have reproduced the compression from our side many times and the ppl under 20% compression ratio look small as follows. Could you please raise another issue about this problem?
>   ![Screenshot 2024-11-21 at 17 24 43](https://private-user-images.githubusercontent.com/40883104/388719409-03b3c383-0352-46d7-83d9-d58d3396db6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3OTcwNTYsIm5iZiI6MTczNDc5Njc1NiwicGF0aCI6Ii80MDg4MzEwNC8zODg3MTk0MDktMDNiM2MzODMtMDM1Mi00NmQ3LTgzZDktZDU4ZDMzOTZkYjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE1NTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYTY4OGUzYmE1YjlmOTI1OWZmYmUyM2JjZjYzZGRjNmE1YWIyNmZiNWYwNTJiOGI5M2Q0YzBiNDgzOTJhNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lHVpncfxEjsjVAmChHGfV9Md15wa1BkW5O1krsMYAgE)
> * For LLaMA-3-8B, we recommend upgrading `transformers` library to `4.45.2` and modifying `LlamaSdpaAttention` rather than `LlamaAttention` as the `SVDLlamaAttention` class. We followed this way to run compression and achieved 14.7 ppl without sequential fine-tuning and 8.16 ppl with sequential fine-tuning. We are also confident with this result since we have reproduced it many times.
> * The LLaMA 2-7B's result is acceptable since in our NeurIPS's version, it has 8.5 ppl without LoRA fine-tuning, which is near 8.25 as you obtained. If you apply sequential LoRA fine-tuning, you can further reduce the ppl to as low as 6.07 in Table 2.
> 
> Currently we are still preparing for the ICLR's rebuttal and paper revision. We will directly update this repo to its final version to align with our revision paper upon accepted.
> 
> Thank you for your understanding and support!

Have you encountered this issue while using the mistral_v1.0 model: Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 40 column 3? Could you please advise on how to resolve it
