### ISSUE TITLE
still fail to apply on llama-13b

### ISSUE THREAD

**Issue by 33answer33** [AIoT-MLSys-Lab/SVD-LLM#7]
Hi, thank you for your reply. But I still get the same problem as mentioned before.
Traceback (most recent call last):
File "/home/xxx/SVD-LLM/SVDLLM_new.py", line 193, in whitening
scaling_matrix_inv = torch.linalg.inv(scaling_diag_matrix)
torch._C._LinAlgError: linalg.inv: The diagonal element 6940 is zero, the inversion could not be completed because the input matrix is singular. "
My python environment is built on requirements.txt. And I run the code on 2 3090 GPUs

**Comment by tuidan** [comment]
Hi, thank you for your feedback.

It seems that the calculation of inversion also needs to be executed in a `double() `precision.

I have updated the code. Now the LLaMA-13B runs successfully on my side as follows:

`python SVDLLM.py --model jeffwan/llama-13b-hf --step 1 --save_path ./`

<img width="853" alt="Screen Shot 2024-05-09 at 23 06 15" src="https://github.com/AIoT-MLSys-Lab/SVD-LLM/assets/40883104/0b0950a5-448b-4669-a0fb-f9141748868a">

`python SVDLLM.py --model_path /local/scratch0/jeffwan_llama_13b_hf_whitening_only_0.8.pt --step 4`

<img width="853" alt="Screen Shot 2024-05-09 at 23 06 04" src="https://github.com/AIoT-MLSys-Lab/SVD-LLM/assets/40883104/fb4977be-a873-4b11-b749-5f1e5457b378">

**Comment by 33answer33** [comment]
I still fail to run it on 3090.Anyway, thank you so much, perhaps I should try using different GPUs..
