### ISSUE TITLE
compresssed checkpoints

### ISSUE THREAD

**Issue by aswanthkrishna** [AIoT-MLSys-Lab/SVD-LLM#8]
is it possible to obtain compressed checkpoints for llama2?

**Comment by tuidan** [comment]
> is it possible to obtain compressed checkpoints for llama2?

Sure, we will open the checkpoints. Stay tuned!

**Comment by NamburiSrinath** [comment]
Hi @tuidan - Incase the checkpoints have been open-sourced, can you please point out to those.

Looking forward, thanks
